 [env]
 TERM = "xterm-256color"
 
 [window]
 padding.x = 10
 padding.y = 10
 decorations = "Buttonless"
 opacity = 0.6
 blur = false
 option_as_alt = "Both"
 startup_mode = "Maximized"
 
 [font]
 normal.family = "MesloLGS Nerd Font Mono"
 size = 14

[general]
 import = [
   "~/.config/alacritty/themes/themes/pastel_dark.toml"
 ]
